# npm cache causes false positives in npm audit due to
# failure to install latest semver match. -Tom
cache:
  npm: false
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
sudo: false
services:
  - docker
  - mongodb

# whitelist
branches:
  only:
    - master
